version: '3'

services:
  grpc-server:
    build:
      context: ./
      dockerfile: ./docker/grpc_server/Dockerfile
    deploy:
      replicas: 1
    image: npuichigo/grpc-server
    volumes:
      - ./testdata:/grpc_gateway_demo/testdata:ro
    networks:
      - overlay
    ports:
      - "9090:9090"

  grpc-gateway:
    build:
      context: ./
      dockerfile: ./docker/grpc_gateway/Dockerfile
    image: npuichigo/grpc-gateway
    command: ["--endpoint", "grpc-server:9090"]
    networks:
      - overlay
    links:
      - grpc-server
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    networks:
      - overlay
    links:
      - grpc-gateway
    ports:
      - "80:80"

networks:
  overlay:
